version: "3.8"

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - db:/var/lib/mysql
    networks:
      - datn
    container_name: datn_db_3.0
    # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysqldb
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8099:80'
    environment:
      PMA_HOST: $PMA_HOST
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    container_name: phpmyadmin
    networks:
      - datn
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - '8080:8080'
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - datn
    container_name: datn_be

volumes:
  db:
networks:
  datn:
    external: true
